DWAPlannerROS:
  global_frame_id: odom

  # Robot Configuration Parameters
  max_trans_vel: 0.2
  min_trans_vel: 0.01
  max_vel_x: 0.2
  min_vel_x: -0.01
  max_vel_y: 0.1
  min_vel_y: -0.1
  max_rot_vel: 0.4
  min_rot_vel: 0.01

  acc_limit_trans: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 1.0

  trans_stopped_vel: 0.01
  rot_stopped_vel: 0.01

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.10
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.1
  vx_samples: 10
  vy_samples: 3 
  vth_samples: 20

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  twirling_scale: 0.0

  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  use_dwa: true
  
  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2

  # Global Plan Parameters
  prune_plan: true

  # Debugging
  publish_cost_grid_pc: false
  publish_traj_pc : false

