controller_frequency: 2.0
controller_patience: 5.0

planner_frequency: 0.0
planner_patience: 5.0

shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5
max_planning_retries: 2

clearing_rotation_allowed: false
recovery_behavior_enabled: true
