global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5
  update_frequency: 2.0
  publish_frequency: 0.0
  static_map: true
  rolling_window: false

  plugins: 
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater, type: "costmap_2d::InflationLayer"}

  obstacles:
    track_unknown_space: true
    footprint_clearing_enabled: true
    
    max_obstacle_height: 0.60
    obstacle_range: 2.5
    raytrace_range: 3.0 
    
    observation_sources: base_scan
    
    base_scan: {
      topic: /base_scan,
      sensor_frame: /laser_link,
      data_type: LaserScan,
      expected_update_rate: 0.2,
      observation_persistence: 0.0,
      clearing: true,
      marking: true,
      min_obstacle_height: -0.10,
      inf_is_valid: false}

  inflater:
    inflation_radius: 0.80
    cost_scaling_factor: 10.0

