local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  transform_tolerance: 0.2
  update_frequency: 3.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  origin_x: -5.0
  origin_y: -5.0

